# -*- coding: utf-8 -*-
"""MIS 315 - Assignment #1 ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FeVGv3STAIoU39cz9o7_DbfoomU0lB-N
"""

#German Corea MIS-315-03  
#Program ask for user's first and last name, then asks for user to select from I.D with numbers 1-6, then asks for the amount to be converted and returns desired converted amount and then loops
def main():


  print('Welcome to the Conversion Program!')
  print()
  #asks for user's first and last name
  name = str(input('What is your first and last name? '))
  print()
  
  #ask for user to select I.D with numbers 1-6
  num_select = int(input(''' Please select from the following list
  1: BTC to U.S. Dollar
  2: Pound sterling to U.S Dollar
  3: Mile to Kilometer
  4: Feet to Meter
  5: Farenheit to Celsius 
  6: kmh to mph
  '''))
  if num_select == 0:
    print("Thank you",name,"for using the Conversion Program, Goodbye!")
  else:
      


    print()

    if num_select < 0 or num_select > 6:
      print("Oops! Looks like a typo. We'll treat that as an end program")
    else:
      conv_val = float(input("Enter amount to be converted: "))
      #Formulas for conversion 
      adj_val1 = (conv_val * 30111)
      adj_val2 = (conv_val * 1.11)
      adj_val3 = (conv_val * 1.609)
      adj_val4 = (conv_val * 0.3048)
      adj_val5 = ((conv_val - 32) * 0.55)
      adj_val6 = ((conv_val * 0.6213714))
      print()
      


    # if-statements and print statements corresponding with num_selct input given by user
      if num_select == 1:
        print(conv_val, 'Bitcoins is equal to', adj_val1, 'U.S Dollars')
      elif num_select == 2:
        print(conv_val, 'Pound Sterling is equal to', adj_val2, 'U.S Dollars')
      elif num_select == 3:
        print(conv_val,'miles is equal to', adj_val3, 'Kilometers')
      elif num_select == 4:
        print(conv_val,'feet is equal to', adj_val4, 'Meters' )
      elif num_select == 5:
        print(conv_val,'degrees farenheit is equal to', adj_val5, 'degrees Celcius')
      elif num_select == 6:
        print(conv_val,'kmh is equal to', adj_val6, 'mph')
      else:
        print("Oops! Looks like a typo. We'll treat that as an end program")
        print()
      restart = input("would you like to run again? ")
      restart = restart.lower()
      if restart == 'yes':
        main()
      else:
        exit()
        print("Thank you", name, "for using the conversion program, Goodbye!")
main()